"""Read Hermes CLI/TUI/desktop sessions from ~/.hermes/state.db for VANOVA sync."""
from __future__ import annotations

import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .logger import get_logger

log = get_logger("maios.hermes_sessions", "hermes-sessions")

CLI_CONV_PREFIX = "cli:"
SOURCE_LABELS = {
    "cli": "Hermes terminal",
    "desktop": "Hermes app",
    "tui": "Hermes TUI",
    "telegram": "Telegram",
    "discord": "Discord",
}

# VANOVA task-execution prompts never belong in the "Sesiones anteriores" chat
# list. They are generated by agent_architect.build_agent_payload() and
# task_queue._execute_task(), not typed by a human — but they run through the
# Hermes CLI, which persists them as sessions alongside real conversations.
_AGENT_TASK_TITLE_MARKERS = (
    "ejecuta tu rutina de análisis",
    "ejecuta tu rutina de analisis",
    "ejecuta la tarea manual asignada al agente",
    "ejecuta la tarea programada asignada al agente",
)


def _is_agent_task_title(title: str) -> bool:
    t = (title or "").strip().lower()
    return any(m in t for m in _AGENT_TASK_TITLE_MARKERS)


TOOL_ACTIVITY: dict[str, tuple[str, str]] = {
    "terminal": ("terminal", "Ejecutando comando en terminal…"),
    "read_file": ("file", "Leyendo archivos…"),
    "write_file": ("file", "Escribiendo archivos…"),
    "patch": ("file", "Modificando archivos…"),
    "search_files": ("search", "Buscando en archivos…"),
    "web_search": ("search", "Buscando en la web…"),
    "web_fetch": ("search", "Consultando página web…"),
    "browser_navigate": ("browser", "Navegando en el navegador…"),
    "browser_click": ("browser", "Interactuando con la página…"),
    "browser_snapshot": ("browser", "Analizando página web…"),
    "shopify": ("shopify", "Consultando Shopify…"),
    "session_search": ("search", "Revisando conversaciones anteriores…"),
    "skill_view": ("spark", "Cargando skill…"),
    "cronjob": ("zap", "Gestionando tareas programadas…"),
    "memory": ("layers", "Actualizando memoria…"),
    "computer_use": ("cpu", "Controlando el escritorio…"),
}


def _db_path() -> Path | None:
    for candidate in (
        Path(os.getenv("LOCALAPPDATA", "")) / "hermes" / "state.db",
        Path.home() / ".hermes" / "state.db",
        Path.home() / "AppData" / "Local" / "hermes" / "state.db",
    ):
        if candidate.is_file():
            return candidate
    return None


def _connect() -> sqlite3.Connection | None:
    path = _db_path()
    if not path:
        return None
    try:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=2.0)
        conn.row_factory = sqlite3.Row
        return conn
    except Exception as exc:
        log.debug("Could not open Hermes state.db: %s", exc)
        return None


def _iso_from_epoch(ts: float | None) -> str:
    if not ts:
        return ""
    try:
        return datetime.fromtimestamp(float(ts), tz=timezone.utc).isoformat()
    except (OSError, OverflowError, ValueError):
        return ""


def _clean_user_content(text: str) -> str:
    if not text:
        return ""
    cleaned = text.strip()
    if cleaned.startswith("[Sistema]"):
        idx = cleaned.rfind("]")
        if idx >= 0:
            cleaned = cleaned[idx + 1 :].strip()
    if cleaned.startswith("[Contexto VANOVA"):
        idx = cleaned.find("\n\n")
        if idx > 0:
            cleaned = cleaned[idx + 2 :]
    return cleaned.strip()


def _title_from_text(text: str, fallback: str) -> str:
    plain = _clean_user_content(text)
    if plain:
        return plain[:60]
    return fallback


def _tool_activity(tool_name: str) -> dict[str, str]:
    step, message = TOOL_ACTIVITY.get(tool_name or "", ("tool", f"Usando herramienta {tool_name or 'Hermes'}…"))
    return {"step": step, "message": message, "source": "hermes_cli"}


def list_sessions(limit: int = 40) -> list[dict[str, Any]]:
    """Recent Hermes sessions from state.db (read-only)."""
    conn = _connect()
    if not conn:
        return []
    try:
        rows = conn.execute(
            """
            SELECT id, source, title, started_at, ended_at, message_count
            FROM sessions
            WHERE COALESCE(message_count, 0) > 0
            ORDER BY started_at DESC
            LIMIT ?
            """,
            (max(1, min(limit, 80)),),
        ).fetchall()
        out: list[dict[str, Any]] = []
        for row in rows:
            sid = str(row["id"] or "")
            if not sid:
                continue
            source = str(row["source"] or "cli")
            title = str(row["title"] or "").strip()
            if not title:
                first_user = conn.execute(
                    """
                    SELECT content FROM messages
                    WHERE session_id = ? AND role = 'user'
                    ORDER BY timestamp ASC LIMIT 1
                    """,
                    (sid,),
                ).fetchone()
                title = _title_from_text(
                    str(first_user["content"] if first_user else ""),
                    f"Sesión {SOURCE_LABELS.get(source, 'Hermes')} · {sid[:16]}",
                )
            if _is_agent_task_title(title):
                continue
            updated = _iso_from_epoch(row["ended_at"] or row["started_at"])
            out.append(
                {
                    "conversation_id": f"{CLI_CONV_PREFIX}{sid}",
                    "hermes_session_id": sid,
                    "title": title,
                    "messages": int(row["message_count"] or 0),
                    "updated_at": updated,
                    "created_at": _iso_from_epoch(row["started_at"]),
                    "source": "hermes_cli",
                    "hermes_source": source,
                    "source_label": SOURCE_LABELS.get(source, source),
                    "read_only": False,
                }
            )
        return out
    except Exception as exc:
        log.warning("Could not list Hermes CLI sessions: %s", exc)
        return []
    finally:
        conn.close()


def get_session_messages(session_id: str) -> list[dict[str, Any]]:
    """Turn Hermes SQLite messages into VANOVA chat request rows."""
    if not session_id:
        return []
    conn = _connect()
    if not conn:
        return []
    try:
        rows = conn.execute(
            """
            SELECT role, content, tool_name, timestamp
            FROM messages
            WHERE session_id = ?
            ORDER BY timestamp ASC, id ASC
            """,
            (session_id,),
        ).fetchall()
    except Exception as exc:
        log.warning("Could not read Hermes session %s: %s", session_id, exc)
        conn.close()
        return []
    conn.close()

    requests: list[dict[str, Any]] = []
    pending_user: str | None = None
    pending_tools: list[dict[str, str]] = []
    turn_idx = 0

    def flush_assistant(content: str, ts: float | None) -> None:
        nonlocal turn_idx, pending_user, pending_tools
        if pending_user is None:
            return
        turn_idx += 1
        activity_log = [
            {**entry, "at": _iso_from_epoch(ts)}
            for entry in pending_tools
        ]
        requests.append(
            {
                "id": f"cli-{session_id}-{turn_idx}",
                "conversation_id": f"{CLI_CONV_PREFIX}{session_id}",
                "message": pending_user,
                "status": "completed",
                "result": (content or "").strip(),
                "activityLog": activity_log,
                "created_at": _iso_from_epoch(ts),
                "processed_at": _iso_from_epoch(ts),
                "source": "hermes_cli",
            }
        )
        pending_user = None
        pending_tools = []

    for row in rows:
        role = str(row["role"] or "")
        content = str(row["content"] or "")
        ts = row["timestamp"]
        if role == "user":
            if pending_user and content:
                flush_assistant("", ts)
            user_text = _clean_user_content(content)
            if user_text:
                pending_user = user_text
            continue
        if role == "tool":
            tool_name = str(row["tool_name"] or "")
            if not tool_name and content.startswith("{"):
                tool_name = "tool"
            act = _tool_activity(tool_name)
            pending_tools.append(act)
            continue
        if role == "assistant" and pending_user is not None:
            if content.strip():
                flush_assistant(content, ts)
            continue

    return requests


def parse_cli_conversation_id(conversation_id: str) -> str:
    if conversation_id.startswith(CLI_CONV_PREFIX):
        return conversation_id[len(CLI_CONV_PREFIX) :]
    return ""
