"""VANOVA Connector — one-shot installer for the owner's PC.

Sets up the venv, installs deps, generates a device key, and writes a
ready-to-edit .env. Run from the connector/ directory on the owner's PC.

Usage:
    python install_connector.py
"""
import os
import sys
import secrets
import subprocess
from pathlib import Path

BASE = Path(__file__).resolve().parent
VENV = BASE / ".venv"
PY = VENV / "Scripts" / "python.exe" if os.name == "nt" else VENV / "bin" / "python"


def run(cmd, cwd=None):
    print(">>", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd or BASE, check=True)


def main():
    print("=" * 60)
    print("VANOVA Connector — instalador para el PC del dueño")
    print("=" * 60)

    # 1. Create venv
    if not PY.exists():
        print("\n[1/4] Creando entorno virtual...")
        run(["uv", "venv", ".venv", "--python", "3.11"])
    else:
        print("\n[1/4] Entorno virtual ya existe.")

    # 2. Install deps
    print("[2/4] Instalando dependencias...")
    run([str(PY), "-m", "pip", "install", "-r", "requirements.txt"])

    # 3. Generate device key + write .env if missing
    print("[3/4] Generando device key y .env...")
    env_path = BASE / ".env"
    if not env_path.exists():
        device_key = secrets.token_urlsafe(32)
        owner_token = secrets.token_urlsafe(32)
        env = f"""# VANOVA Connector config (generated by installer)
MAIOS_CLOUD_URL=https://maios.up.railway.app
MAIOS_DEVICE_KEY={device_key}
MAIOS_WORKSPACE_ID=
MAIOS_OWNER_TOKEN={owner_token}
HERMES_CLI=
HERMES_API_KEY=
MAIOS_HEARTBEAT_SECONDS=30
"""
        env_path.write_text(env, encoding="utf-8")
        print("   .env creado. Edítalo para poner MAIOS_CLOUD_URL y HERMES_CLI.")
    else:
        print("   .env ya existe (no se sobrescribe).")

    # 4. Verify
    print("[4/4] Verificando...")
    run([str(PY), "-c", "import httpx, dotenv; print('   deps OK')"])

    print("\n" + "=" * 60)
    print("Instalación completada.")
    print("Siguientes pasos:")
    print("  1. Edita connector/.env: MAIOS_CLOUD_URL y HERMES_CLI")
    print("  2. Arranca: .venv\\Scripts\\python.exe connector.py")
    print("  3. Registra MAIOS_DEVICE_KEY en el dashboard (Settings → Devices)")
    print("=" * 60)


if __name__ == "__main__":
    main()
